// AUTOGENERATED Components module
pub mod badge;
pub mod button;
pub mod card;
pub mod input;
pub mod modal;
pub mod pagination;
pub mod progress;
pub mod separator;
pub mod skeleton;
pub mod textarea;
