configfile: config/config.yml

executor: slurm

use-conda: true
jobs: 12
latency-wait: 60

default-resources:
  runtime: "15m"
  gres: "gpu:1"
  mem_mb: 2000
  slurm_partition: "lrz-v100x2,lrz-dgx-1-p100x8,lrz-dgx-1-v100x8"
  slurm_account: default
  tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

set-resources:
  finetune_heads_only:
    runtime: "24h"
    mem_mb: 72000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  finetune_lora:
    runtime: "24h"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  finetune_accgrad_lora:
    runtime: "48h"
    mem_mb: 72000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  finetune_align_lora:
    runtime: "48h"
    mem_mb: 72000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  predict:
    runtime: "90m"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  predict_proba:
    runtime: "90m"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  representation_eval_export_embeddings:
    runtime: "90m"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0 # prevent slurm executor from setting --ntasks-per-gpu

  resplit_mmseqs_cluster:
    runtime: "4h"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0

  resplit_foldseek_cluster:
    runtime: "12h"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0

  download_prostt5:
    runtime: "30m"
    mem_mb: 4000

  leakage_mmseqs_search:
    runtime: "1h"
    mem_mb: 16000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0

  leakage_foldseek_search:
    runtime: "2h"
    mem_mb: 64000
    gres: "gpu:1"
    slurm_partition: "lrz-hgx-h100-94x4,lrz-hgx-a100-80x4,lrz-dgx-a100-80x8"
    slurm_account: default
    tasks_per_gpu: 0
