#!/usr/bin/env python3
"""Upload fine-tuned ONNX models and PyTorch checkpoints to HuggingFace Hub.

Reads the pipeline configuration to determine which ONNX models to upload,
stages them into a HuggingFace-compatible directory layout using symlinks
(to avoid duplicating large files), discovers all training runs under
``results/train/`` and includes their minimal trainable-parameter PyTorch
checkpoints, generates a model card (README.md), and uploads via
``huggingface_hub``.

Usage::

    python scripts/upload_to_huggingface.py --config config/config.yml
    python scripts/upload_to_huggingface.py --config config/config.yml --dry-run
    python scripts/upload_to_huggingface.py --config config/config.yml --repo-id user/repo

The script expects that ONNX exports and training outputs have already
been generated by the Snakemake pipeline (i.e. the ``results/onnx_export/``
and ``results/train/`` trees are populated).

Staging uses ``.hf_staging/`` in the project root (gitignored) with
symlinks back to the original files, so no disk space is consumed for
the large model artifacts.

Authentication: set the ``HF_TOKEN`` environment variable or run
``huggingface-cli login`` beforehand.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Ensure the project source tree is importable when running standalone
# ---------------------------------------------------------------------------
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT / "src"))

from mutafitup.hf_naming import BACKBONE_HF_PREFIXES, hf_model_name  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("upload_to_huggingface")

_STAGING_DIR = _PROJECT_ROOT / ".hf_staging"


# ── Model card template ──────────────────────────────────────────────

MODEL_CARD_TEMPLATE = """\
---
license: other
license_name: cambrian-open
license_link: https://huggingface.co/{repo_id}/blob/main/CAMBRIAN_OPEN_LICENSE.md
tags:
  - protein-language-model
  - onnx
  - fine-tuning
  - multi-task
  - esm
---

# {repo_id}

Multi-task LoRA fine-tuned ONNX models derived from
[ESM-C 300M](https://huggingface.co/EvolutionaryScale/esmc-300m-2024-12)
by [EvolutionaryScale](https://www.evolutionaryscale.ai/).

Built with ESM.

## ONNX Models

{model_table}

Each ONNX model directory contains:
- `model.onnx` -- merged ONNX model (LoRA weights folded into backbone)
- `export_metadata.json` -- task configuration and preprocessing settings
- `normalization_stats.json` -- per-task normalization statistics
- `tokenizer/` -- HuggingFace tokenizer files
- `history.json` -- training history (per-epoch metrics)
- `best_checkpoints.json` -- checkpoint selection metadata

## PyTorch Checkpoints

The `checkpoints/` directory contains minimal trainable-parameter
PyTorch checkpoints for **all** training runs ({num_runs} runs across
{num_sections} training sections). These checkpoints contain only the
parameters that were updated during fine-tuning (LoRA adapters and task
heads), not the frozen backbone weights.

Each run directory (`checkpoints/{{section}}/{{run}}/`) contains:
- `history.json` -- training history
- `best_checkpoints.json` -- checkpoint selection metadata
- `best_overall_model/model.pt` -- best checkpoint by overall metric
- `best_loss_overall_model/model.pt` -- best checkpoint by overall loss
- `best_task_models/{{task}}/model.pt` -- best checkpoint per task metric
- `best_loss_task_models/{{task}}/model.pt` -- best checkpoint per task loss

To load a checkpoint, use `MultitaskModel.load_trainable_weights()` from
the [mutafitup](https://github.com/Moomboh/mutafitup) training library.

## License

The ESMC 300M base model is licensed under the
[EvolutionaryScale Cambrian Open License Agreement](CAMBRIAN_OPEN_LICENSE.md).

Fine-tuning code and pipeline are licensed under the MIT License.

See [NOTICE](NOTICE) for full attribution details.
"""


# ── Symlink helpers ──────────────────────────────────────────────────


def _symlink_file(src: Path, dest: Path) -> None:
    """Create a symlink at ``dest`` pointing to ``src``."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() or dest.is_symlink():
        dest.unlink()
    os.symlink(src.resolve(), dest)


def _symlink_tree(src: Path, dest: Path) -> None:
    """Symlink an entire directory tree file-by-file.

    Recreates the directory structure under ``dest`` and creates
    symlinks for each file. This is needed because
    ``huggingface_hub.upload_folder`` traverses the tree and needs
    real directory entries.
    """
    if not src.is_dir():
        return
    for item in src.rglob("*"):
        if item.is_file():
            rel = item.relative_to(src)
            _symlink_file(item, dest / rel)


# ── Helpers ───────────────────────────────────────────────────────────


def _load_config(config_path: str) -> dict:
    """Load and return the YAML config."""
    with open(config_path) as f:
        return yaml.safe_load(f)


def _read_export_metadata(export_dir: Path) -> dict | None:
    """Read export_metadata.json from an ONNX export directory."""
    meta_path = export_dir / "export_metadata.json"
    if not meta_path.exists():
        return None
    with open(meta_path) as f:
        return json.load(f)


def _build_model_table(models: list[dict]) -> str:
    """Build a Markdown table of uploaded models."""
    lines = [
        "| Model | Section | Tasks | Variant |",
        "|-------|---------|-------|---------|",
    ]
    for m in models:
        tasks = ", ".join(m["tasks"][:3])
        if len(m["tasks"]) > 3:
            tasks += f", ... ({len(m['tasks'])} total)"
        lines.append(
            f"| `{m['hf_name']}` | {m['section']} | {tasks} | {m['variant']} |"
        )
    return "\n".join(lines)


def _stage_model(
    entry: dict,
    onnx_export_base: Path,
    staging_dir: Path,
) -> dict | None:
    """Symlink a single ONNX model's files into the staging directory.

    Also symlinks ``history.json`` and ``best_checkpoints.json`` from the
    corresponding training run directory for convenience.

    Returns a metadata dict for the model table, or None if the export
    directory is missing.
    """
    section = entry["section"]
    run_id = entry["id"]
    variant = entry["variant"]

    export_dir = onnx_export_base / section / run_id / variant
    if not export_dir.exists():
        log.warning("Export directory not found, skipping: %s", export_dir)
        return None

    metadata = _read_export_metadata(export_dir)
    if metadata is None:
        log.warning("No export_metadata.json in %s, skipping", export_dir)
        return None

    backbone = metadata["base_checkpoint"]

    if backbone not in BACKBONE_HF_PREFIXES:
        log.warning(
            "Backbone %r not supported for HF naming, skipping %s/%s/%s",
            backbone,
            section,
            run_id,
            variant,
        )
        return None

    name = hf_model_name(backbone, section, run_id, variant)
    model_dir = staging_dir / name
    model_dir.mkdir(parents=True, exist_ok=True)

    # Symlink ONNX export files
    for item in export_dir.iterdir():
        dest = model_dir / item.name
        if item.is_dir():
            _symlink_tree(item, dest)
        else:
            _symlink_file(item, dest)

    # Symlink training metadata from the training directory (convenience)
    train_dir = _PROJECT_ROOT / "results" / "train" / section / run_id
    for fname in ("history.json", "best_checkpoints.json"):
        src = train_dir / fname
        if src.exists():
            _symlink_file(src, model_dir / fname)
            log.info("  Included %s from %s", fname, src)
        else:
            log.warning("  %s not found at %s", fname, src)

    tasks = sorted(metadata.get("tasks", {}).keys())

    log.info("Staged ONNX model: %s", name)

    return {
        "hf_name": name,
        "section": section,
        "run_id": run_id,
        "variant": variant,
        "backbone": backbone,
        "tasks": tasks,
    }


# Checkpoint directories to include from each training run.
# These contain only minimal trainable-parameter state dicts.
_CHECKPOINT_DIRS = [
    "best_overall_model",
    "best_loss_overall_model",
    "best_task_models",
    "best_loss_task_models",
]

# Metadata files to include from each training run.
_CHECKPOINT_FILES = [
    "history.json",
    "best_checkpoints.json",
]


def _stage_all_checkpoints(
    train_base: Path,
    staging_dir: Path,
) -> int:
    """Symlink minimal trainable-parameter PyTorch checkpoints for all runs.

    Scans ``train_base`` for all ``{section}/{run}/`` directories and
    symlinks checkpoint artifacts into
    ``staging_dir/checkpoints/{section}/{run}/``.

    Returns the number of runs staged.
    """
    checkpoints_root = staging_dir / "checkpoints"
    staged_count = 0

    if not train_base.exists():
        log.warning("Training directory does not exist: %s", train_base)
        return 0

    for section_dir in sorted(train_base.iterdir()):
        if not section_dir.is_dir():
            continue
        section = section_dir.name

        for run_dir in sorted(section_dir.iterdir()):
            if not run_dir.is_dir():
                continue
            run_id = run_dir.name

            dest_dir = checkpoints_root / section / run_id
            has_content = False

            # Symlink metadata files
            for fname in _CHECKPOINT_FILES:
                src = run_dir / fname
                if src.exists():
                    _symlink_file(src, dest_dir / fname)
                    has_content = True
                else:
                    log.warning(
                        "  checkpoints/%s/%s: %s not found", section, run_id, fname
                    )

            # Symlink checkpoint directories
            for dirname in _CHECKPOINT_DIRS:
                src = run_dir / dirname
                if src.is_dir():
                    _symlink_tree(src, dest_dir / dirname)
                    has_content = True
                else:
                    log.warning(
                        "  checkpoints/%s/%s: %s/ not found", section, run_id, dirname
                    )

            if has_content:
                log.info("Staged checkpoints: %s/%s", section, run_id)
                staged_count += 1

    return staged_count


def _stage_license_files(staging_dir: Path) -> None:
    """Symlink license and attribution files to the staging directory root."""
    project_root = _PROJECT_ROOT

    # Cambrian Open License
    src = project_root / "THIRD_PARTY_LICENSES" / "CAMBRIAN_OPEN_LICENSE.md"
    if src.exists():
        _symlink_file(src, staging_dir / "CAMBRIAN_OPEN_LICENSE.md")
    else:
        log.warning("License file not found: %s", src)

    # NOTICE
    notice = project_root / "NOTICE"
    if notice.exists():
        _symlink_file(notice, staging_dir / "NOTICE")
    else:
        log.warning("NOTICE file not found: %s", notice)


def _write_model_card(
    staging_dir: Path,
    repo_id: str,
    models: list[dict],
    num_runs: int,
    num_sections: int,
) -> None:
    """Generate the HuggingFace model card (README.md)."""
    table = _build_model_table(models)
    card = MODEL_CARD_TEMPLATE.format(
        repo_id=repo_id,
        model_table=table,
        num_runs=num_runs,
        num_sections=num_sections,
    )
    readme = staging_dir / "README.md"
    readme.write_text(card)
    log.info("Wrote model card: %s", readme)


def _write_hf_manifest(staging_dir: Path, models: list[dict]) -> None:
    """Generate a models.json manifest for the HF repo.

    This manifest uses the HF model name as the ``id`` (matching the
    subdirectory name in the repo) so consumers can locate model files.
    """
    entries = []
    for m in models:
        model_dir = staging_dir / m["hf_name"]
        metadata = _read_export_metadata(model_dir)

        external_data = (model_dir / "model.onnx.data").exists()

        entries.append(
            {
                "id": m["hf_name"],
                "label": m["hf_name"],
                "section": m["section"],
                "run_id": m["run_id"],
                "variant": m["variant"],
                "backbone": m["backbone"],
                "tasks": m["tasks"],
                "web_compatible": not external_data,
            }
        )

    manifest = {"models": entries}
    manifest_path = staging_dir / "models.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    log.info("Wrote HF manifest with %d model(s): %s", len(entries), manifest_path)


# ── Main ──────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Upload fine-tuned ONNX models and PyTorch checkpoints to HuggingFace Hub."
    )
    parser.add_argument(
        "--config",
        required=True,
        help="Path to the pipeline config YAML (e.g. config/config.yml)",
    )
    parser.add_argument(
        "--repo-id",
        default=None,
        help="Override the HuggingFace repo ID from config",
    )
    parser.add_argument(
        "--onnx-export-dir",
        default="results/onnx_export",
        help="Root directory of ONNX exports (default: results/onnx_export)",
    )
    parser.add_argument(
        "--train-dir",
        default="results/train",
        help="Root directory of training runs (default: results/train)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Stage files but do not upload to HuggingFace",
    )
    parser.add_argument(
        "--commit-message",
        default=None,
        help="Custom commit message for the HF upload",
    )
    args = parser.parse_args(argv)

    config = _load_config(args.config)

    # Resolve repo ID
    repo_id = args.repo_id
    if repo_id is None:
        hf_config = config.get("huggingface", {})
        repo_id = hf_config.get("repo_id")
    if not repo_id:
        log.error(
            "No repo_id specified. Set huggingface.repo_id in config or use --repo-id."
        )
        sys.exit(1)

    # Resolve exports to upload
    onnx_entries = config.get("onnx_export", [])
    if not onnx_entries:
        log.error("No onnx_export entries in config. Nothing to upload.")
        sys.exit(1)

    onnx_export_base = Path(args.onnx_export_dir)
    if not onnx_export_base.exists():
        log.error("ONNX export directory does not exist: %s", onnx_export_base)
        sys.exit(1)

    train_base = Path(args.train_dir)

    # Prepare staging directory (gitignored, in project root)
    staging_dir = _STAGING_DIR
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True)
    log.info("Staging directory: %s", staging_dir)

    try:
        # Stage ONNX model files (symlinks)
        staged_models = []
        for entry in onnx_entries:
            result = _stage_model(entry, onnx_export_base, staging_dir)
            if result is not None:
                staged_models.append(result)

        if not staged_models:
            log.error("No ONNX models were staged. Check export directories.")
            sys.exit(1)

        # Stage all training run checkpoints (symlinks)
        num_runs = _stage_all_checkpoints(train_base, staging_dir)

        # Count distinct sections
        num_sections = 0
        checkpoints_root = staging_dir / "checkpoints"
        if checkpoints_root.exists():
            num_sections = sum(1 for d in checkpoints_root.iterdir() if d.is_dir())

        # Stage license + attribution files (symlinks)
        _stage_license_files(staging_dir)

        # Generate model card and HF manifest (written, not symlinked)
        _write_model_card(staging_dir, repo_id, staged_models, num_runs, num_sections)
        _write_hf_manifest(staging_dir, staged_models)

        log.info(
            "Staged %d ONNX model(s) + %d checkpoint run(s) for upload to %s",
            len(staged_models),
            num_runs,
            repo_id,
        )

        if args.dry_run:
            log.info("Dry run -- listing staged files:")
            for p in sorted(staging_dir.rglob("*")):
                if p.is_symlink() or p.is_file():
                    rel = p.relative_to(staging_dir)
                    target = p.resolve()
                    size_mb = target.stat().st_size / (1024 * 1024)
                    log.info("  %s (%.1f MB)", rel, size_mb)
            log.info("Dry run complete. No files were uploaded.")
            return

        # Upload to HuggingFace
        try:
            from huggingface_hub import HfApi
        except ImportError:
            log.error(
                "huggingface_hub is not installed. "
                "Install it with: pip install huggingface_hub"
            )
            sys.exit(1)

        api = HfApi()

        # Create repo if it doesn't exist
        api.create_repo(
            repo_id=repo_id,
            repo_type="model",
            exist_ok=True,
        )

        commit_message = args.commit_message or (
            f"Upload {len(staged_models)} ONNX model(s) + "
            f"{num_runs} checkpoint run(s): "
            + ", ".join(m["hf_name"] for m in staged_models)
        )

        log.info("Uploading to %s ...", repo_id)
        api.upload_folder(
            repo_id=repo_id,
            folder_path=str(staging_dir),
            commit_message=commit_message,
            repo_type="model",
        )

        log.info("Upload complete: https://huggingface.co/%s", repo_id)

    finally:
        # Clean up staging directory
        if staging_dir.exists():
            shutil.rmtree(staging_dir)
            log.info("Cleaned up staging directory: %s", staging_dir)


if __name__ == "__main__":
    main()
