/// ONNX inference backend for mutafitup models.
///
/// Provides a platform-abstracted `InferenceBackend` trait with two
/// implementations: `NativeBackend` (ort + ONNX Runtime) for desktop
/// and `WebBackend` (ort-web + onnxruntime-web) for the browser.

pub mod preprocessing;
pub mod tokenizer;

#[cfg(not(target_arch = "wasm32"))]
pub mod native;

#[cfg(target_arch = "wasm32")]
pub mod web;

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ── Execution provider selection ──

/// User-selectable ONNX Runtime execution provider.
///
/// Variants are ordered by priority (best first). The UI dropdown
/// is populated from [`available_eps()`] which probes the platform
/// and returns only the EPs that are actually usable.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum EpChoice {
    CoreML,
    DirectML,
    WebGPU,
    Cpu,
}

impl std::fmt::Display for EpChoice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CoreML => write!(f, "CoreML"),
            Self::DirectML => write!(f, "DirectML"),
            Self::WebGPU => write!(f, "WebGPU"),
            Self::Cpu => write!(f, "CPU"),
        }
    }
}

impl EpChoice {
    /// Stable identifier used as the `<option value="...">` in the UI dropdown.
    pub fn id(&self) -> &'static str {
        match self {
            Self::CoreML => "coreml",
            Self::DirectML => "directml",
            Self::WebGPU => "webgpu",
            Self::Cpu => "cpu",
        }
    }

    /// Parse from the stable identifier returned by [`id()`].
    pub fn from_id(s: &str) -> Option<Self> {
        match s {
            "coreml" => Some(Self::CoreML),
            "directml" => Some(Self::DirectML),
            "webgpu" => Some(Self::WebGPU),
            "cpu" => Some(Self::Cpu),
            _ => None,
        }
    }
}

// ── Types matching models.json (model manifest) ──

/// A single entry in the model manifest generated by the pipeline.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct ModelManifestEntry {
    pub id: String,
    pub label: String,
    pub section: String,
    pub run_id: String,
    pub variant: String,
    pub backbone: String,
    pub tasks: Vec<String>,
    /// Whether this model can be loaded by onnxruntime-web (i.e. no
    /// external data file exceeding the 2 GB protobuf limit).
    #[serde(default = "default_web_compatible")]
    pub web_compatible: bool,
}

fn default_web_compatible() -> bool {
    true
}

/// Top-level model manifest listing all available ONNX exports.
#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct ModelManifest {
    pub models: Vec<ModelManifestEntry>,
}

// ── Types matching export_metadata.json ──

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreprocessingConfig {
    pub space_separate: bool,
    pub prefix: Option<String>,
    pub char_replacements: HashMap<String, String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TaskConfig {
    pub problem_type: String,
    pub level: String,
    pub num_outputs: usize,
    pub output_name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct ExportMetadata {
    pub base_checkpoint: String,
    pub backbone_class: String,
    pub preprocessing: PreprocessingConfig,
    /// Number of leading special tokens (e.g. CLS) before the amino acid
    /// positions in the tokenizer output. Used to align per-residue
    /// predictions with the input sequence.
    ///
    /// - ESM/ESM-C (CLS $A EOS): 1
    /// - T5 ($A EOS): 0
    ///
    /// Defaults to 0 for backward compatibility with older exports.
    #[serde(default)]
    pub cls_token_offset: usize,
    pub tasks: HashMap<String, TaskConfig>,
    pub inputs: Vec<String>,
    pub outputs: Vec<String>,
    pub opset_version: u32,
}

// ── Types matching normalization_stats.json ──

/// Per-task normalization statistics for a regression task.
///
/// During training, regression labels are normalized by dividing by
/// `scale_factor` (max-absolute scaling). Model outputs must be
/// multiplied by `scale_factor` to recover training-label values.
///
/// Some tasks also export an optional `display_scale_factor` that converts
/// training-label values to the final user-facing unit.
#[derive(Debug, Clone, Deserialize, PartialEq)]
#[allow(dead_code)]
pub struct TaskNormStats {
    pub label_min: f64,
    pub label_max: f64,
    pub scale_factor: f64,
    #[serde(default = "default_display_scale_factor")]
    pub display_scale_factor: f64,
}

fn default_display_scale_factor() -> f64 {
    1.0
}

/// Per-task normalization statistics keyed by task name.
/// Only regression tasks have entries.
pub type NormalizationStats = HashMap<String, TaskNormStats>;

// ── Types matching task_labels.json ──

/// Human-readable metadata for a single task.
///
/// Classification tasks have `class_labels` (ordered by class index).
/// Regression tasks have `unit` (e.g. "°C", "Z-score").
#[derive(Debug, Clone, Deserialize, PartialEq)]
pub struct TaskLabelInfo {
    pub description: String,
    #[serde(default)]
    pub class_labels: Option<Vec<String>>,
    #[serde(default)]
    pub unit: Option<String>,
}

/// Human-readable label metadata keyed by task name.
pub type TaskLabels = HashMap<String, TaskLabelInfo>;

/// Per-task prediction results keyed by task name.
pub type Predictions = HashMap<String, Vec<f32>>;

/// Denormalize regression predictions in-place using normalization stats.
///
/// For each task in `predictions`, if `norm_stats` contains a matching
/// entry, all values are multiplied by the task's `scale_factor` and then by
/// its optional `display_scale_factor`. Classification tasks (which have no
/// entry) pass through unchanged.
pub fn denormalize_predictions(predictions: &mut Predictions, norm_stats: &NormalizationStats) {
    for (task_name, values) in predictions.iter_mut() {
        if let Some(stats) = norm_stats.get(task_name) {
            let scale = (stats.scale_factor * stats.display_scale_factor) as f32;
            for v in values.iter_mut() {
                *v *= scale;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{denormalize_predictions, NormalizationStats, Predictions, TaskNormStats};

    #[test]
    fn denormalize_predictions_applies_display_scale_factor() {
        let mut predictions = Predictions::from([
            ("meltome".to_string(), vec![0.5]),
            ("secstr".to_string(), vec![1.0, 0.0]),
        ]);
        let norm_stats = NormalizationStats::from([(
            "meltome".to_string(),
            TaskNormStats {
                label_min: 2.76,
                label_max: 9.9,
                scale_factor: 9.9,
                display_scale_factor: 10.0,
            },
        )]);

        denormalize_predictions(&mut predictions, &norm_stats);

        assert_eq!(predictions["meltome"], vec![49.5]);
        assert_eq!(predictions["secstr"], vec![1.0, 0.0]);
    }

    #[test]
    fn missing_display_scale_factor_defaults_to_one() {
        let json = r#"{
            "meltome": {
                "label_min": 2.76,
                "label_max": 9.9,
                "scale_factor": 9.9
            }
        }"#;
        let norm_stats: NormalizationStats = serde_json::from_str(json).unwrap();
        let mut predictions = Predictions::from([("meltome".to_string(), vec![0.5])]);

        denormalize_predictions(&mut predictions, &norm_stats);

        assert_eq!(norm_stats["meltome"].display_scale_factor, 1.0);
        assert_eq!(predictions["meltome"], vec![4.95]);
    }
}

/// Split flat batch predictions into per-sequence results.
///
/// The ONNX model outputs flat tensors for the whole batch:
/// - Per-protein tasks: `[batch_size, num_outputs]` flattened to `batch_size * num_outputs`
/// - Per-residue tasks: `[batch_size, seq_len, num_outputs]` flattened to `batch_size * seq_len * num_outputs`
///
/// `seq_len` is the padded sequence length from the tokenizer (same for all
/// sequences in the batch due to padding).
///
/// For per-residue tasks, the leading `cls_token_offset` positions (e.g.
/// CLS token for ESM-C) are stripped so that position 0 in the output
/// corresponds to the first amino acid.
pub fn split_batch_predictions(
    preds: &Predictions,
    metadata: &ExportMetadata,
    batch_size: usize,
    seq_len: usize,
) -> Vec<Predictions> {
    let mut per_sequence: Vec<Predictions> = (0..batch_size).map(|_| Predictions::new()).collect();
    let cls_offset = metadata.cls_token_offset;

    for (task_name, task_config) in &metadata.tasks {
        let Some(values) = preds.get(task_name) else {
            continue;
        };

        let num_outputs = task_config.num_outputs;
        let stride = if task_config.level == "per_residue" {
            seq_len * num_outputs
        } else {
            num_outputs
        };

        for i in 0..batch_size {
            let start = i * stride;
            let end = (start + stride).min(values.len());
            if start < values.len() {
                if task_config.level == "per_residue" && cls_offset > 0 {
                    // Skip leading special token positions (e.g. CLS) so
                    // position 0 aligns with the first amino acid.
                    let skip = cls_offset * num_outputs;
                    let trimmed_start = start + skip;
                    if trimmed_start < end {
                        per_sequence[i]
                            .insert(task_name.clone(), values[trimmed_start..end].to_vec());
                    }
                } else {
                    per_sequence[i].insert(task_name.clone(), values[start..end].to_vec());
                }
            }
        }
    }

    per_sequence
}

// ── Platform-specific backend re-export ──

#[allow(unused_imports)]
#[cfg(not(target_arch = "wasm32"))]
pub use native::NativeModelHandle as Backend;

#[allow(unused_imports)]
#[cfg(target_arch = "wasm32")]
pub use web::WebBackend as Backend;
